-- third party plugins
require('plugins_config/aerial')
require('plugins_config/comment')
require('plugins_config/copilot')
require('plugins_config/devicons')
require('plugins_config/efe')
require('plugins_config/indent_blankline')
require('plugins_config/leap')
require('plugins_config/lsp_config')
require('plugins_config/surround')
require('plugins_config/treesitter')
require('plugins_config/ts_autotags')
require('plugins_config/telescope')
require('plugins_config/neoclip')
require('plugins_config/blink')
require('plugins_config/dap')

-- custom scripts
require('custom/theme')
require('custom/mappings')
require('custom/yazi/yazi_setup')
require('custom/term/term')
require('custom/statusline')
require('custom/buffers')
